/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fayettevilletechgpacalculator;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.text.DecimalFormat;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author oreng
 */
public class GPACalculator extends javax.swing.JFrame {

    /**
     * Creates new form GPACalculator
     */
    
    public GPACalculator() {
        initComponents();
        //Set save boc components to invisible-----------------
        jPanel2.setVisible(false);
        saveDoc_textField.setVisible(false);
        save_boxLabel.setVisible(false);
        save_button.setVisible(false);
        //-----------------------------------------------------
        // <editor-fold defaultstate="collapsed" desc="Load Combo Box Array"> 
        //Load brick types to String array
        String[] brickOptions = {
        "    ","A","B","C","D","F"};     
        //Add array to combo box
        LetterGrade1_comboBox.setModel(new DefaultComboBoxModel(brickOptions)); 
        LetterGrade2_comboBox.setModel(new DefaultComboBoxModel(brickOptions));
        LetterGrade3_comboBox.setModel(new DefaultComboBoxModel(brickOptions));
        LetterGrade4_comboBox.setModel(new DefaultComboBoxModel(brickOptions));
        LetterGrade5_comboBox.setModel(new DefaultComboBoxModel(brickOptions));
        LetterGrade6_comboBox.setModel(new DefaultComboBoxModel(brickOptions));
        LetterGrade7_comboBox.setModel(new DefaultComboBoxModel(brickOptions));
        LetterGrade8_comboBox.setModel(new DefaultComboBoxModel(brickOptions));
        
         // </editor-fold>  
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        displayStudentInfo_textArea = new javax.swing.JScrollPane();
        studentInfo = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        studentName_textField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        calc_button = new javax.swing.JButton();
        reset_button = new javax.swing.JButton();
        creditsClass8_textBox = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        creditsClass7_textBox = new javax.swing.JTextField();
        creditsClass6_textBox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        creditsClass5_textBox = new javax.swing.JTextField();
        creditsClass4_textBox = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        creditsClass2_textBox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        summerJRButton = new javax.swing.JRadioButton();
        fallJRButton = new javax.swing.JRadioButton();
        springJRButton = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        creditsClass3_textBox = new javax.swing.JTextField();
        creditsClass1_textBox = new javax.swing.JTextField();
        LetterGrade1_comboBox = new javax.swing.JComboBox<>();
        LetterGrade2_comboBox = new javax.swing.JComboBox<>();
        LetterGrade3_comboBox = new javax.swing.JComboBox<>();
        LetterGrade4_comboBox = new javax.swing.JComboBox<>();
        LetterGrade5_comboBox = new javax.swing.JComboBox<>();
        LetterGrade6_comboBox = new javax.swing.JComboBox<>();
        LetterGrade7_comboBox = new javax.swing.JComboBox<>();
        LetterGrade8_comboBox = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        saveDoc_textField = new javax.swing.JTextField();
        save_boxLabel = new javax.swing.JLabel();
        saveDoc_label = new javax.swing.JLabel();
        save_button = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        saveFIle_jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));
        setForeground(new java.awt.Color(0, 204, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(241, 183, 37));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        studentInfo.setColumns(20);
        studentInfo.setRows(5);
        studentInfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        displayStudentInfo_textArea.setViewportView(studentInfo);

        jPanel1.add(displayStudentInfo_textArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 300, 190));

        jLabel13.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jLabel13.setText("Students Name");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        studentName_textField.setText(" ");
        studentName_textField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(studentName_textField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 170, -1));

        jLabel14.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jLabel14.setText("Semester");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        calc_button.setText("Calculate");
        calc_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(calc_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, -1, -1));

        reset_button.setText("Reset");
        reset_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(reset_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 510, -1, -1));

        creditsClass8_textBox.setText("0");
        creditsClass8_textBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        creditsClass8_textBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                creditsClass8_textBoxMouseClicked(evt);
            }
        });
        jPanel1.add(creditsClass8_textBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 60, -1));

        jLabel5.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jLabel5.setText("Class 8");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, 20));

        jLabel7.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jLabel7.setText("Class 7");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, 20));

        creditsClass7_textBox.setText("0");
        creditsClass7_textBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        creditsClass7_textBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                creditsClass7_textBoxMouseClicked(evt);
            }
        });
        jPanel1.add(creditsClass7_textBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 60, -1));

        creditsClass6_textBox.setText("0");
        creditsClass6_textBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        creditsClass6_textBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                creditsClass6_textBoxMouseClicked(evt);
            }
        });
        jPanel1.add(creditsClass6_textBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 60, -1));

        jLabel4.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jLabel4.setText("Class 6");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, 20));

        jLabel8.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jLabel8.setText("Class 5");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, 20));

        creditsClass5_textBox.setText("0");
        creditsClass5_textBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        creditsClass5_textBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                creditsClass5_textBoxMouseClicked(evt);
            }
        });
        jPanel1.add(creditsClass5_textBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 60, -1));

        creditsClass4_textBox.setText("0");
        creditsClass4_textBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        creditsClass4_textBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                creditsClass4_textBoxMouseClicked(evt);
            }
        });
        jPanel1.add(creditsClass4_textBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 60, -1));

        jLabel6.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jLabel6.setText("Class 4");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, 20));

        jLabel3.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jLabel3.setText("Class 3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, 20));

        creditsClass2_textBox.setText("0");
        creditsClass2_textBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        creditsClass2_textBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                creditsClass2_textBoxMouseClicked(evt);
            }
        });
        jPanel1.add(creditsClass2_textBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 60, -1));

        jLabel2.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jLabel2.setText("Class 2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, 20));

        jLabel1.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jLabel1.setText("Class 1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, 20));

        jLabel10.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jLabel10.setText("Credits");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, -1, -1));

        jLabel9.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jLabel9.setText("Letter Grade");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        summerJRButton.setBackground(new java.awt.Color(241, 183, 37));
        summerJRButton.setText("Summer");
        jPanel1.add(summerJRButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        fallJRButton.setBackground(new java.awt.Color(241, 183, 37));
        fallJRButton.setText("Fall");
        jPanel1.add(fallJRButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        springJRButton.setBackground(new java.awt.Color(241, 183, 37));
        springJRButton.setText("Spring");
        jPanel1.add(springJRButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        jLabel12.setFont(new java.awt.Font("Microsoft Himalaya", 0, 75)); // NOI18N
        jLabel12.setText("GPA Calculator");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 340, 60));

        jLabel11.setFont(new java.awt.Font("Microsoft Himalaya", 1, 24)); // NOI18N
        jLabel11.setText("FTCC Grading Scale");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, -1, -1));

        creditsClass3_textBox.setText("0");
        creditsClass3_textBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        creditsClass3_textBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                creditsClass3_textBoxMouseClicked(evt);
            }
        });
        jPanel1.add(creditsClass3_textBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 60, -1));

        creditsClass1_textBox.setText("0");
        creditsClass1_textBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        creditsClass1_textBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                creditsClass1_textBoxMouseClicked(evt);
            }
        });
        jPanel1.add(creditsClass1_textBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 60, -1));

        LetterGrade1_comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(LetterGrade1_comboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        LetterGrade2_comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(LetterGrade2_comboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, -1));

        LetterGrade3_comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(LetterGrade3_comboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

        LetterGrade4_comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(LetterGrade4_comboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, -1));

        LetterGrade5_comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(LetterGrade5_comboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, -1, -1));

        LetterGrade6_comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(LetterGrade6_comboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, -1, -1));

        LetterGrade7_comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(LetterGrade7_comboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, -1, -1));

        LetterGrade8_comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(LetterGrade8_comboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fayettevilletechgpacalculator/FTCC Logo3.PNG"))); // NOI18N
        jLabel15.setText(" ");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 80));

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("Grade \tGrade points per credit hour \tExplanation\nA \t4 \tExcellent\nB \t3 \tVery Good\nC \t2 \tSatisfactory\nD \t1 \tPoor\nF \t0 \tFailing");
        jTextArea2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(jTextArea2);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 580, 230));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fayettevilletechgpacalculator/FtccLogoTrojan2.png"))); // NOI18N
        jLabel16.setText(" ");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, -1, 180));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(saveDoc_textField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 190, -1));

        save_boxLabel.setText("Name Document:");
        jPanel2.add(save_boxLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        saveDoc_label.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        saveDoc_label.setText("Save Document");
        jPanel2.add(saveDoc_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        save_button.setText("Save");
        save_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(save_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 320, 100));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fayettevilletechgpacalculator/FtccEstabLogo1.png"))); // NOI18N
        jLabel17.setText(" ");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 600, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 800));

        jMenu1.setText("File");

        saveFIle_jMenuItem1.setText("Save");
        saveFIle_jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveFIle_jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(saveFIle_jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calc_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc_buttonActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        
        String input;
        double credits = 0.0;
        double points = 0.0;
        String semesterType;
       
        String [] letterGradeArray = new String[8];
        if(!LetterGrade1_comboBox.getSelectedItem().equals("")&&LetterGrade1_comboBox.getSelectedItem().equals("A")||LetterGrade1_comboBox.getSelectedItem().equals("B")||LetterGrade1_comboBox.getSelectedItem().equals("C")||LetterGrade1_comboBox.getSelectedItem().equals("D")
            ||LetterGrade1_comboBox.getSelectedItem().equals("F"))
        {
            input = creditsClass1_textBox.getText();
            credits += CheckTextBox(input); 
            letterGradeArray[0] = LetterGrade1_comboBox.getSelectedItem().toString();
            points += GetPoints(points,LetterGrade1_comboBox.getSelectedItem().toString(),credits);
            System.out.println(points);
        }
        else
        {
            creditsClass1_textBox.setText("0");
        }
        if(!LetterGrade2_comboBox.getSelectedItem().equals("")&&LetterGrade2_comboBox.getSelectedItem().equals("A")||LetterGrade2_comboBox.getSelectedItem().equals("B")||LetterGrade2_comboBox.getSelectedItem().equals("C")||LetterGrade2_comboBox.getSelectedItem().equals("D")
            ||LetterGrade2_comboBox.getSelectedItem().equals("F"))
        {
            input = creditsClass2_textBox.getText();
            credits = CheckTextBox(input);
            letterGradeArray[0] = LetterGrade2_comboBox.getSelectedItem().toString();
            points += GetPoints(points,LetterGrade2_comboBox.getSelectedItem().toString(),credits);
            System.out.println(points);
        }
        else
        {
            creditsClass2_textBox.setText("0");
        }
        if(!LetterGrade3_comboBox.getSelectedItem().equals("")&&LetterGrade3_comboBox.getSelectedItem().equals("A")||LetterGrade3_comboBox.getSelectedItem().equals("B")||LetterGrade3_comboBox.getSelectedItem().equals("C")||LetterGrade3_comboBox.getSelectedItem().equals("D")
            ||LetterGrade3_comboBox.getSelectedItem().equals("F"))
        {
            input = creditsClass3_textBox.getText();
            credits = CheckTextBox(input);
            letterGradeArray[0] = LetterGrade3_comboBox.getSelectedItem().toString();
            points += GetPoints(points,LetterGrade3_comboBox.getSelectedItem().toString(),credits);
            System.out.println(points);
        }
        else
        {
            creditsClass3_textBox.setText("0");
        }
        if(!LetterGrade4_comboBox.getSelectedItem().equals("")&&LetterGrade4_comboBox.getSelectedItem().equals("A")||LetterGrade4_comboBox.getSelectedItem().equals("B")||LetterGrade4_comboBox.getSelectedItem().equals("C")||LetterGrade4_comboBox.getSelectedItem().equals("D")
            ||LetterGrade4_comboBox.getSelectedItem().equals("F"))
        {
            input = creditsClass4_textBox.getText();
            credits = CheckTextBox(input);
            letterGradeArray[0] = LetterGrade4_comboBox.getSelectedItem().toString();
            points += GetPoints(points,LetterGrade4_comboBox.getSelectedItem().toString(),credits);
            System.out.println(points);
        }
        else
        {
            creditsClass4_textBox.setText("0");
        }
        if(!LetterGrade5_comboBox.getSelectedItem().equals("")&&LetterGrade5_comboBox.getSelectedItem().equals("A")||LetterGrade5_comboBox.getSelectedItem().equals("B")||LetterGrade5_comboBox.getSelectedItem().equals("C")||LetterGrade5_comboBox.getSelectedItem().equals("D")
            ||LetterGrade5_comboBox.getSelectedItem().equals("F"))
        {
            input = creditsClass5_textBox.getText();
            credits = CheckTextBox(input);
            letterGradeArray[0] = LetterGrade5_comboBox.getSelectedItem().toString();
            points += GetPoints(points,LetterGrade5_comboBox.getSelectedItem().toString(),credits);
            System.out.println(points);
        }
        else
        {
            creditsClass5_textBox.setText("0");
        }
        if(!LetterGrade6_comboBox.getSelectedItem().equals("")&&LetterGrade6_comboBox.getSelectedItem().equals("A")||LetterGrade6_comboBox.getSelectedItem().equals("B")||LetterGrade6_comboBox.getSelectedItem().equals("C")||LetterGrade6_comboBox.getSelectedItem().equals("D")
            ||LetterGrade6_comboBox.getSelectedItem().equals("F"))
        {
            input = creditsClass6_textBox.getText();
            credits = CheckTextBox(input);
            letterGradeArray[0] = LetterGrade6_comboBox.getSelectedItem().toString();
            points += GetPoints(points,LetterGrade6_comboBox.getSelectedItem().toString(),credits);
            System.out.println(points);
        }
        else
        {
            creditsClass6_textBox.setText("0");
        }
        if(!LetterGrade7_comboBox.getSelectedItem().equals("")&&LetterGrade7_comboBox.getSelectedItem().equals("A")||LetterGrade7_comboBox.getSelectedItem().equals("B")||LetterGrade7_comboBox.getSelectedItem().equals("C")||LetterGrade7_comboBox.getSelectedItem().equals("D")
            ||LetterGrade7_comboBox.getSelectedItem().equals("F"))
        {
            input = creditsClass7_textBox.getText();
            credits = CheckTextBox(input);
            letterGradeArray[0] = LetterGrade7_comboBox.getSelectedItem().toString();
            points += GetPoints(points,LetterGrade7_comboBox.getSelectedItem().toString(),credits);
            System.out.println(points);
        }
        else
        {
            creditsClass7_textBox.setText("0");
        }
        if(!LetterGrade8_comboBox.getSelectedItem().equals("")&&LetterGrade8_comboBox.getSelectedItem().equals("A")||LetterGrade8_comboBox.getSelectedItem().equals("B")||LetterGrade8_comboBox.getSelectedItem().equals("C")||LetterGrade8_comboBox.getSelectedItem().equals("D")
            ||LetterGrade8_comboBox.getSelectedItem().equals("F"))
        {
            input = creditsClass8_textBox.getText();
            credits = CheckTextBox(input);
            letterGradeArray[0] = LetterGrade8_comboBox.getSelectedItem().toString();
            points += GetPoints(points,LetterGrade8_comboBox.getSelectedItem().toString(),credits);
            System.out.println(points);
        }
        else
        {
            creditsClass8_textBox.setText("0");
        }
        semesterType = GetSemster();
        System.out.println(points);
        DecimalFormat df = new DecimalFormat("0.00");
        credits = GetCredits();
        System.out.println(credits);
        input = String.valueOf(df.format(GetGPA(points,credits)));
        System.out.println(String.valueOf(GetGPA(points,credits)));
        studentInfo.setText("Student Semester Information\n**********************************\n"
                + "Semester: " + semesterType +
                "\nName: "+ studentName_textField.getText() +                
                "\nStudent GPA: " + input
                );
         
    }//GEN-LAST:event_calc_buttonActionPerformed
    private Double GetGPA(double points,double credits){
       
        
        double GPA = points/credits;         
        return GPA;
    }
    private String GetSemster()
    {
        String sType = "";
        if(springJRButton.isSelected() == true){
            sType = "Spring";
        }
        else if(fallJRButton.isSelected() == true){
            sType = "Fall";
        }
        else if(summerJRButton.isSelected() == true){
            sType = "Summer";
        }
        return sType;
    }
    private double GetCredits(){
        String input;
        double credits = 0;
        input = creditsClass1_textBox.getText();
        credits += CheckTextBox(input);   
        input = creditsClass2_textBox.getText();
        credits += CheckTextBox(input);   
        input = creditsClass3_textBox.getText();
        credits += CheckTextBox(input);   
        input = creditsClass4_textBox.getText();
        credits += CheckTextBox(input);   
        input = creditsClass5_textBox.getText();
        credits += CheckTextBox(input);   
        input = creditsClass6_textBox.getText();
        credits += CheckTextBox(input);   
        input = creditsClass7_textBox.getText();
        credits += CheckTextBox(input);   
        input = creditsClass8_textBox.getText();
        credits += CheckTextBox(input);   
        
        return credits;
    }
    private double CheckTextBox(String input)
    {
        double credits = 0.0;
         if(input.matches("[a-zA-Z]+") || input.equals(""))
         {
                 
         }
         else
         {
            credits = Double.parseDouble(input); 
         } 
        return credits;
    }
    private static double GetPoints(double points, String letter,double credits)
    {
        switch(letter){
            case "":            
                points = 0;                
                break;
            case "A":
            case "a":
                points = credits * 4;                
                break;
            case "B":
            case "b":
                points = credits * 3;
                break;
            case "C":
            case "c":
                points = credits * 2;
                break;
            case "D":
            case "d":
                points = credits * 1;
                break;
            case "F":
            case "f":
                points = credits * 0;
                break;
        }
        return points;
    }
    private void reset_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_buttonActionPerformed
        // <editor-fold defaultstate="collapsed" desc="Reset Text Boxes">
        
        creditsClass1_textBox.setText("0");
        creditsClass2_textBox.setText("0");
        creditsClass3_textBox.setText("0");
        creditsClass4_textBox.setText("0");
        creditsClass5_textBox.setText("0");
        creditsClass6_textBox.setText("0");
        creditsClass7_textBox.setText("0");
        creditsClass8_textBox.setText("0");
        
//        studentInfo.setText("");
        // </editor-fold>
    }//GEN-LAST:event_reset_buttonActionPerformed

    private void saveFIle_jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveFIle_jMenuItem1ActionPerformed
        jPanel2.setVisible(true);
        saveDoc_textField.setVisible(true);
        save_boxLabel.setVisible(true);
        save_button.setVisible(true);
    }//GEN-LAST:event_saveFIle_jMenuItem1ActionPerformed

    private void save_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_buttonActionPerformed
    // TODO add your handling code here:
     // TODO add your handling code here:
            //Document saveFile = new Document(); 

         try {
            String input = "";

            input = saveDoc_textField.getText();
            //input = JOptionPane.showInputDialog(null,"Enter Document Name");
            //Create new file and writer and buff objects
            File file = new File( "GPADocuments/" + input +".txt");        
            FileWriter writer = new FileWriter(file);        
            BufferedWriter buff = new BufferedWriter(writer); 
            PrintWriter printWriter = new PrintWriter(buff);
            file.createNewFile();
            printWriter.print(studentInfo.getText());
            printWriter.print("\n*****************************\n");
            buff.close();
            writer.close();
            printWriter.close();
            jPanel2.setVisible(false);
            saveDoc_textField.setVisible(false);
            save_boxLabel.setVisible(false);
            save_button.setVisible(false);
            
           

         }
           catch (Exception ex) {
             //Logger.getLogger(BrickProgram.class.getName()).log(Level.SEVERE, null, ex);
         }
        
    }//GEN-LAST:event_save_buttonActionPerformed
// <editor-fold defaultstate="collapsed" desc="Clear credit Text Box">

    private void creditsClass2_textBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditsClass2_textBoxMouseClicked
        // Clear text box to allow user to enter number of credits
        creditsClass2_textBox.setText("");
    }//GEN-LAST:event_creditsClass2_textBoxMouseClicked

    private void creditsClass3_textBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditsClass3_textBoxMouseClicked
        // Clear text box to allow user to enter number of credits
        creditsClass3_textBox.setText("");
    }//GEN-LAST:event_creditsClass3_textBoxMouseClicked

    private void creditsClass4_textBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditsClass4_textBoxMouseClicked
        // Clear text box to allow user to enter number of credits
        creditsClass4_textBox.setText("");
    }//GEN-LAST:event_creditsClass4_textBoxMouseClicked

    private void creditsClass5_textBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditsClass5_textBoxMouseClicked
        // Clear text box to allow user to enter number of credits
        creditsClass5_textBox.setText("");
    }//GEN-LAST:event_creditsClass5_textBoxMouseClicked

    private void creditsClass1_textBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditsClass1_textBoxMouseClicked
         // Clear text box to allow user to enter number of credits
        creditsClass1_textBox.setText("");
    }//GEN-LAST:event_creditsClass1_textBoxMouseClicked

    private void creditsClass6_textBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditsClass6_textBoxMouseClicked
         // Clear text box to allow user to enter number of credits
        creditsClass6_textBox.setText("");
    }//GEN-LAST:event_creditsClass6_textBoxMouseClicked

    private void creditsClass7_textBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditsClass7_textBoxMouseClicked
         // Clear text box to allow user to enter number of credits
        creditsClass7_textBox.setText(" ");
    }//GEN-LAST:event_creditsClass7_textBoxMouseClicked

    private void creditsClass8_textBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditsClass8_textBoxMouseClicked
         // Clear text box to allow user to enter number of credits
        creditsClass8_textBox.setText("");
    }//GEN-LAST:event_creditsClass8_textBoxMouseClicked
                               // </editor-fold>    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GPACalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GPACalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GPACalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GPACalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GPACalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> LetterGrade1_comboBox;
    private javax.swing.JComboBox<String> LetterGrade2_comboBox;
    private javax.swing.JComboBox<String> LetterGrade3_comboBox;
    private javax.swing.JComboBox<String> LetterGrade4_comboBox;
    private javax.swing.JComboBox<String> LetterGrade5_comboBox;
    private javax.swing.JComboBox<String> LetterGrade6_comboBox;
    private javax.swing.JComboBox<String> LetterGrade7_comboBox;
    private javax.swing.JComboBox<String> LetterGrade8_comboBox;
    private javax.swing.JButton calc_button;
    private javax.swing.JTextField creditsClass1_textBox;
    private javax.swing.JTextField creditsClass2_textBox;
    private javax.swing.JTextField creditsClass3_textBox;
    private javax.swing.JTextField creditsClass4_textBox;
    private javax.swing.JTextField creditsClass5_textBox;
    private javax.swing.JTextField creditsClass6_textBox;
    private javax.swing.JTextField creditsClass7_textBox;
    private javax.swing.JTextField creditsClass8_textBox;
    private javax.swing.JScrollPane displayStudentInfo_textArea;
    private javax.swing.JRadioButton fallJRButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JButton reset_button;
    private javax.swing.JLabel saveDoc_label;
    private javax.swing.JTextField saveDoc_textField;
    private javax.swing.JMenuItem saveFIle_jMenuItem1;
    private javax.swing.JLabel save_boxLabel;
    private javax.swing.JButton save_button;
    private javax.swing.JRadioButton springJRButton;
    private javax.swing.JTextArea studentInfo;
    private javax.swing.JTextField studentName_textField;
    private javax.swing.JRadioButton summerJRButton;
    // End of variables declaration//GEN-END:variables
}
