/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package brickapplication_orengoanthony;
import java.awt.Color;
import java.awt.Component;
import java.awt.PopupMenu;
import java.io.BufferedWriter;
import java.io.*;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
public class BrickProgram extends javax.swing.JFrame {

    /**
     * Creates new form BrickProgram
     */
     // <editor-fold defaultstate="collapsed" desc="Array Lists"> 
         public ArrayList locationNamesArrayList = new ArrayList();
         public ArrayList brickDim = new ArrayList();
         public ArrayList sectionDim = new ArrayList();
         public ArrayList voidDim = new ArrayList();
         public ArrayList brickTracker = new ArrayList();
         public ArrayList<Double> brickTotalList = new ArrayList();
         // </editor-fold> 
         
     // <editor-fold defaultstate="collapsed" desc="Variables"> 
         //public DefaultListModel listModel = new DefaultListModel();
         public DefaultListModel model = new DefaultListModel();
         public Object[] itemObject = new  Object[10];  
         public JList locationNamesJList;
         double inches = 12,mortarGap = 0, totalBricks = 0;
         double brickArea,brickLength, brickWidth;//Brick Formula Area = L * W  2-3/4" x 7-5/8"
         double sectionArea,sectionLength, sectionWidth;//Sect Formula Area = L * W
         double deadSpaceArea,deadSpaceLength, deadSpaceWidth;//DS Formula Area = L * W
         public double finalBrickNumber = 0.0;
         double countBricks = 0.0;
         // </editor-fold> 
     Document saveFile = new Document();  
    
     public BrickProgram() {
        initComponents();
         
        // <editor-fold defaultstate="collapsed" desc="Load Combo Box Array"> 
        //Load brick types to String array
        String[] brickOptions = {
        "","Modular(2-1/4 x 7-5/8","Standard(2-1/4  x 8",
        "Jumbo Modular(2-3/4 x 7-5/8","Jumbo Standard(2-3/4 x 8",
        
        "Jumbo Standard PLT3(2-5/8 x 8","Slim Jumbo Modular(2-3/4 x 7-5/8",
        
        "Queen(2-3/4 x 9-5/8","Roman(1-5/8 x 11-5/8",
        
        "Norman(2-1/4 x 11-5/8","Jumbo Norman(2-3/4 x 11-5/8",
        
        "Slim Jumbo Norman(2-3/4 x 11-5/8","Modular Economo(3-5/8 x 7-5/8",
        
        "Utilty(3-5/8 x 11-5/8","Monarch(3-5/8 x 15-5/8",
        
        "Quad(7-5/8 x 7-5/8","Ambasador(2-1/4 x 15-5/8",
        "Double Utilty(3-5/8 x 15-5/8","Double Monarch(7-5/8 x 15-5/8",
        
        "Thru-Wall 1(3-5/8 x 15-5/8","Thru-Wall 2(3-5/8 x 15-5/8",
        
        "Thru-Wall 3(7-5/8 x 15-5/8"};
     
     
        //Add array to combo box
        brickTypesComboBox.setModel(new DefaultComboBoxModel(brickOptions)); 
        
         // </editor-fold>   
        
        saveDocPanel.setVisible(false);//Set saveDocPanel to invisible
        okButton.setVisible(false);//Set ok button(saveDocPanel) to invisible 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainProgramPanel = new javax.swing.JPanel();
        saveDocPanel = new javax.swing.JPanel();
        percentLabel = new javax.swing.JLabel();
        saveDocProgressBar = new javax.swing.JProgressBar();
        enterDocNameTextBox = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        enterDocNameLabel = new javax.swing.JLabel();
        saveDocTitle = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        sectionDimPanel = new javax.swing.JPanel();
        dimensions1 = new javax.swing.JLabel();
        lengthDimLabel3 = new javax.swing.JLabel();
        widthDimLabel1 = new javax.swing.JLabel();
        lengthSectionTextField = new javax.swing.JTextField();
        widthSectionTextField = new javax.swing.JTextField();
        brickDimPanel = new javax.swing.JPanel();
        dimensions3 = new javax.swing.JLabel();
        lengthDimLabel5 = new javax.swing.JLabel();
        widthDimLabel3 = new javax.swing.JLabel();
        lengthBrickTextField1 = new javax.swing.JTextField();
        widthBrickTextField1 = new javax.swing.JTextField();
        brickTypesComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        locationBrickTrackerTitle = new javax.swing.JLabel();
        finishButton = new javax.swing.JButton();
        displayListButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        brickList = new javax.swing.JList<>();
        clearButton = new javax.swing.JButton();
        javax.swing.JButton instructionsButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        stepFiveLabel = new javax.swing.JLabel();
        stepSixLabel = new javax.swing.JLabel();
        totalBricksButton = new javax.swing.JButton();
        displayTotalBricksTextBox = new javax.swing.JTextField();
        constructionImage = new javax.swing.JLabel();
        calculateBricksNeeded = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        stepOneLabel = new javax.swing.JLabel();
        stepTwoLabel = new javax.swing.JLabel();
        brickResultField = new javax.swing.JTextField();
        stepFourLabel = new javax.swing.JLabel();
        locationPanel = new javax.swing.JPanel();
        dimensions = new javax.swing.JLabel();
        lengthDimLabel2 = new javax.swing.JLabel();
        locationNameTextField = new javax.swing.JTextField();
        voidDimPanel = new javax.swing.JPanel();
        dimensions2 = new javax.swing.JLabel();
        lengthDimLabel4 = new javax.swing.JLabel();
        widthDimLabel2 = new javax.swing.JLabel();
        lengthDeadSpaceTextField = new javax.swing.JTextField();
        widthDeadSpaceTextField = new javax.swing.JTextField();
        voidDimTotal = new javax.swing.JTextField();
        totalLabel2 = new javax.swing.JLabel();
        stepThreeLabel1 = new javax.swing.JLabel();
        backgroundLabel = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newFormOption = new javax.swing.JMenuItem();
        openButton = new javax.swing.JMenuItem();
        saveFormOption = new javax.swing.JMenuItem();
        printDoc = new javax.swing.JMenuItem();
        exitOption = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        instructionsOption = new javax.swing.JMenuItem();
        legendItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        mainProgramPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        saveDocPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        saveDocPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        percentLabel.setText("0%");
        saveDocPanel.add(percentLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, 20));
        saveDocPanel.add(saveDocProgressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 20));

        enterDocNameTextBox.setText(" ");
        saveDocPanel.add(enterDocNameTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 150, -1));

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        saveDocPanel.add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 60, -1));

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        saveDocPanel.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 70, -1));

        enterDocNameLabel.setText("Enter Document Name");
        saveDocPanel.add(enterDocNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        saveDocTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        saveDocTitle.setText("Save Document");
        saveDocPanel.add(saveDocTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        okButton.setText("Ok");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        saveDocPanel.add(okButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 100, -1));

        mainProgramPanel.add(saveDocPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 320, 120));

        sectionDimPanel.setBackground(new java.awt.Color(0, 153, 153));
        sectionDimPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));

        dimensions1.setBackground(new java.awt.Color(255, 255, 255));
        dimensions1.setFont(new java.awt.Font("Microsoft Himalaya", 1, 28)); // NOI18N
        dimensions1.setText("Section Dimensions");

        lengthDimLabel3.setFont(new java.awt.Font("Microsoft Himalaya", 1, 28)); // NOI18N
        lengthDimLabel3.setText("Length(ft)");

        widthDimLabel1.setFont(new java.awt.Font("Microsoft Himalaya", 1, 28)); // NOI18N
        widthDimLabel1.setText("Width(ft)");

        lengthSectionTextField.setFont(new java.awt.Font("Microsoft Himalaya", 1, 24)); // NOI18N
        lengthSectionTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        lengthSectionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lengthSectionTextFieldActionPerformed(evt);
            }
        });

        widthSectionTextField.setFont(new java.awt.Font("Microsoft Himalaya", 1, 24)); // NOI18N
        widthSectionTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout sectionDimPanelLayout = new javax.swing.GroupLayout(sectionDimPanel);
        sectionDimPanel.setLayout(sectionDimPanelLayout);
        sectionDimPanelLayout.setHorizontalGroup(
            sectionDimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sectionDimPanelLayout.createSequentialGroup()
                .addGroup(sectionDimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sectionDimPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(dimensions1, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
                    .addGroup(sectionDimPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(sectionDimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(widthDimLabel1)
                            .addComponent(lengthDimLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(sectionDimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(widthSectionTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(lengthSectionTextField))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        sectionDimPanelLayout.setVerticalGroup(
            sectionDimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sectionDimPanelLayout.createSequentialGroup()
                .addComponent(dimensions1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(sectionDimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lengthSectionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lengthDimLabel3))
                .addGap(14, 14, 14)
                .addGroup(sectionDimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(widthDimLabel1)
                    .addComponent(widthSectionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        mainProgramPanel.add(sectionDimPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 230, 170));

        brickDimPanel.setBackground(new java.awt.Color(0, 153, 153));
        brickDimPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));

        dimensions3.setBackground(new java.awt.Color(255, 255, 255));
        dimensions3.setFont(new java.awt.Font("Microsoft Himalaya", 1, 28)); // NOI18N
        dimensions3.setText("Brick Dimensions");

        lengthDimLabel5.setFont(new java.awt.Font("Microsoft Himalaya", 1, 28)); // NOI18N
        lengthDimLabel5.setText("Length(in)");

        widthDimLabel3.setFont(new java.awt.Font("Microsoft Himalaya", 1, 28)); // NOI18N
        widthDimLabel3.setText("Width(in)");

        lengthBrickTextField1.setFont(new java.awt.Font("Microsoft Himalaya", 1, 24)); // NOI18N
        lengthBrickTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        lengthBrickTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lengthBrickTextField1ActionPerformed(evt);
            }
        });

        widthBrickTextField1.setFont(new java.awt.Font("Microsoft Himalaya", 1, 24)); // NOI18N
        widthBrickTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));

        brickTypesComboBox.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        brickTypesComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brickTypesComboBoxActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Microsoft Himalaya", 0, 18)); // NOI18N
        jLabel2.setText("Choose Brick Type.");
        jLabel2.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Microsoft Himalaya", 0, 18)); // NOI18N
        jLabel3.setText("Enter Brick Dimensions.");

        javax.swing.GroupLayout brickDimPanelLayout = new javax.swing.GroupLayout(brickDimPanel);
        brickDimPanel.setLayout(brickDimPanelLayout);
        brickDimPanelLayout.setHorizontalGroup(
            brickDimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brickDimPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(brickDimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dimensions3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(brickDimPanelLayout.createSequentialGroup()
                        .addGroup(brickDimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(brickDimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(brickDimPanelLayout.createSequentialGroup()
                                    .addComponent(widthDimLabel3)
                                    .addGap(28, 28, 28)
                                    .addComponent(widthBrickTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(brickDimPanelLayout.createSequentialGroup()
                                    .addComponent(lengthDimLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lengthBrickTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 46, Short.MAX_VALUE))
                    .addComponent(brickTypesComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        brickDimPanelLayout.setVerticalGroup(
            brickDimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brickDimPanelLayout.createSequentialGroup()
                .addComponent(dimensions3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(brickTypesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(1, 1, 1)
                .addGroup(brickDimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lengthDimLabel5)
                    .addComponent(lengthBrickTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(brickDimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(widthDimLabel3)
                    .addComponent(widthBrickTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        mainProgramPanel.add(brickDimPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 260, 220));

        jLabel1.setFont(new java.awt.Font("Microsoft Himalaya", 1, 48)); // NOI18N
        jLabel1.setText("Final Step");
        mainProgramPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 400, 180, 40));

        locationBrickTrackerTitle.setFont(new java.awt.Font("Microsoft Himalaya", 1, 48)); // NOI18N
        locationBrickTrackerTitle.setText("Brick Tracker");
        mainProgramPanel.add(locationBrickTrackerTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 80, 240, -1));

        finishButton.setBackground(new java.awt.Color(0, 204, 0));
        finishButton.setFont(new java.awt.Font("Microsoft Himalaya", 1, 24)); // NOI18N
        finishButton.setText("Finish");
        finishButton.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        finishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishButtonActionPerformed(evt);
            }
        });
        mainProgramPanel.add(finishButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 450, 110, 40));

        displayListButton.setFont(new java.awt.Font("Microsoft Himalaya", 1, 24)); // NOI18N
        displayListButton.setText("Display List");
        displayListButton.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        displayListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayListButtonActionPerformed(evt);
            }
        });
        mainProgramPanel.add(displayListButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 450, 120, 40));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));

        brickList.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(brickList);

        mainProgramPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 120, 270, 280));

        clearButton.setBackground(new java.awt.Color(255, 51, 0));
        clearButton.setFont(new java.awt.Font("Microsoft Himalaya", 1, 24)); // NOI18N
        clearButton.setText("Clear Form");
        clearButton.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        mainProgramPanel.add(clearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 650, 110, 50));

        instructionsButton.setFont(new java.awt.Font("Microsoft Himalaya", 1, 24)); // NOI18N
        instructionsButton.setText("Instructions");
        instructionsButton.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        instructionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructionsButtonActionPerformed(evt);
            }
        });
        mainProgramPanel.add(instructionsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 650, 120, 50));

        closeButton.setFont(new java.awt.Font("Microsoft Himalaya", 1, 24)); // NOI18N
        closeButton.setText("Close");
        closeButton.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        mainProgramPanel.add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 670, 100, 40));

        stepFiveLabel.setFont(new java.awt.Font("Microsoft Himalaya", 1, 48)); // NOI18N
        stepFiveLabel.setText("Step 5");
        mainProgramPanel.add(stepFiveLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, -1, -1));

        stepSixLabel.setFont(new java.awt.Font("Microsoft Himalaya", 1, 48)); // NOI18N
        stepSixLabel.setText("Step 6");
        mainProgramPanel.add(stepSixLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 490, -1, -1));

        totalBricksButton.setFont(new java.awt.Font("Microsoft Himalaya", 1, 24)); // NOI18N
        totalBricksButton.setText("Total Bricks");
        totalBricksButton.setToolTipText("");
        totalBricksButton.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        totalBricksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalBricksButtonActionPerformed(evt);
            }
        });
        mainProgramPanel.add(totalBricksButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 480, 110, 50));

        displayTotalBricksTextBox.setFont(new java.awt.Font("Microsoft Himalaya", 1, 36)); // NOI18N
        displayTotalBricksTextBox.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        mainProgramPanel.add(displayTotalBricksTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 540, 350, 80));

        constructionImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brickapplication_orengoanthony/Images/ConstructionImage2.jpg"))); // NOI18N
        constructionImage.setText("jLabel4");
        constructionImage.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        mainProgramPanel.add(constructionImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 530, 320));

        calculateBricksNeeded.setFont(new java.awt.Font("Microsoft Himalaya", 1, 24)); // NOI18N
        calculateBricksNeeded.setText("Add to Total");
        calculateBricksNeeded.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        calculateBricksNeeded.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateBricksNeededActionPerformed(evt);
            }
        });
        mainProgramPanel.add(calculateBricksNeeded, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 330, 110, 50));

        titleLabel.setBackground(new java.awt.Color(0, 255, 255));
        titleLabel.setFont(new java.awt.Font("Microsoft Himalaya", 1, 75)); // NOI18N
        titleLabel.setText("JAVA BRICK PROGRAM");
        mainProgramPanel.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        stepOneLabel.setBackground(new java.awt.Color(0, 255, 255));
        stepOneLabel.setFont(new java.awt.Font("Microsoft Himalaya", 1, 48)); // NOI18N
        stepOneLabel.setText("Step 1");
        mainProgramPanel.add(stepOneLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        stepTwoLabel.setBackground(new java.awt.Color(0, 255, 255));
        stepTwoLabel.setFont(new java.awt.Font("Microsoft Himalaya", 1, 48)); // NOI18N
        stepTwoLabel.setText("Step 2");
        mainProgramPanel.add(stepTwoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, -1));

        brickResultField.setFont(new java.awt.Font("Microsoft Himalaya", 1, 36)); // NOI18N
        brickResultField.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        mainProgramPanel.add(brickResultField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 390, 350, 70));

        stepFourLabel.setBackground(new java.awt.Color(0, 255, 255));
        stepFourLabel.setFont(new java.awt.Font("Microsoft Himalaya", 1, 48)); // NOI18N
        stepFourLabel.setText("Step 4");
        mainProgramPanel.add(stepFourLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 70, -1, -1));

        locationPanel.setBackground(new java.awt.Color(0, 153, 153));
        locationPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));

        dimensions.setBackground(new java.awt.Color(255, 255, 255));
        dimensions.setFont(new java.awt.Font("Microsoft Himalaya", 1, 28)); // NOI18N
        dimensions.setText("Location Name");

        lengthDimLabel2.setFont(new java.awt.Font("Microsoft Himalaya", 1, 28)); // NOI18N
        lengthDimLabel2.setText("Name");

        locationNameTextField.setFont(new java.awt.Font("Microsoft Himalaya", 1, 24)); // NOI18N
        locationNameTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        locationNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationNameTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout locationPanelLayout = new javax.swing.GroupLayout(locationPanel);
        locationPanel.setLayout(locationPanelLayout);
        locationPanelLayout.setHorizontalGroup(
            locationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(locationPanelLayout.createSequentialGroup()
                .addGroup(locationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(locationPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(dimensions, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
                    .addGroup(locationPanelLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(lengthDimLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(locationNameTextField)))
                .addContainerGap())
        );
        locationPanelLayout.setVerticalGroup(
            locationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(locationPanelLayout.createSequentialGroup()
                .addComponent(dimensions, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(locationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(locationPanelLayout.createSequentialGroup()
                        .addComponent(lengthDimLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(locationPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(locationNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(209, 209, 209))))
        );

        mainProgramPanel.add(locationPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 210, 170));

        voidDimPanel.setBackground(new java.awt.Color(0, 153, 153));
        voidDimPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));

        dimensions2.setBackground(new java.awt.Color(255, 255, 255));
        dimensions2.setFont(new java.awt.Font("Microsoft Himalaya", 1, 28)); // NOI18N
        dimensions2.setText("Void Dimensions");

        lengthDimLabel4.setFont(new java.awt.Font("Microsoft Himalaya", 1, 28)); // NOI18N
        lengthDimLabel4.setText("Length(ft)");

        widthDimLabel2.setFont(new java.awt.Font("Microsoft Himalaya", 1, 28)); // NOI18N
        widthDimLabel2.setText("Width(ft)");

        lengthDeadSpaceTextField.setFont(new java.awt.Font("Microsoft Himalaya", 1, 24)); // NOI18N
        lengthDeadSpaceTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        lengthDeadSpaceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lengthDeadSpaceTextFieldActionPerformed(evt);
            }
        });

        widthDeadSpaceTextField.setFont(new java.awt.Font("Microsoft Himalaya", 1, 24)); // NOI18N
        widthDeadSpaceTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));

        voidDimTotal.setText("jTextField1");

        totalLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalLabel2.setText("Total");

        javax.swing.GroupLayout voidDimPanelLayout = new javax.swing.GroupLayout(voidDimPanel);
        voidDimPanel.setLayout(voidDimPanelLayout);
        voidDimPanelLayout.setHorizontalGroup(
            voidDimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(voidDimPanelLayout.createSequentialGroup()
                .addComponent(totalLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(voidDimTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(voidDimPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(voidDimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(voidDimPanelLayout.createSequentialGroup()
                        .addComponent(dimensions2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, voidDimPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(voidDimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(voidDimPanelLayout.createSequentialGroup()
                                .addComponent(widthDimLabel2)
                                .addGap(26, 26, 26))
                            .addGroup(voidDimPanelLayout.createSequentialGroup()
                                .addComponent(lengthDimLabel4)
                                .addGap(18, 18, 18)))
                        .addGroup(voidDimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(widthDeadSpaceTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lengthDeadSpaceTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46))))
        );
        voidDimPanelLayout.setVerticalGroup(
            voidDimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(voidDimPanelLayout.createSequentialGroup()
                .addComponent(dimensions2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(voidDimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lengthDimLabel4)
                    .addComponent(lengthDeadSpaceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(voidDimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(widthDimLabel2)
                    .addComponent(widthDeadSpaceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(152, 152, 152)
                .addGroup(voidDimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voidDimTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalLabel2))
                .addContainerGap())
        );

        mainProgramPanel.add(voidDimPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 120, 230, 170));

        stepThreeLabel1.setBackground(new java.awt.Color(0, 255, 255));
        stepThreeLabel1.setFont(new java.awt.Font("Microsoft Himalaya", 1, 48)); // NOI18N
        stepThreeLabel1.setText("Step 3");
        mainProgramPanel.add(stepThreeLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, -1, -1));

        backgroundLabel.setBackground(new java.awt.Color(255, 255, 255));
        backgroundLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        backgroundLabel.setForeground(new java.awt.Color(255, 255, 255));
        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brickapplication_orengoanthony/Images/BrickImage2.jpg"))); // NOI18N
        backgroundLabel.setText("jLabel1");
        backgroundLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 0)));
        mainProgramPanel.add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 730));

        menuBar.setBackground(new java.awt.Color(0, 153, 153));
        menuBar.setForeground(new java.awt.Color(255, 255, 255));

        fileMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fileMenu.setText("File");
        fileMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        newFormOption.setText("New Form");
        newFormOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newFormOptionActionPerformed(evt);
            }
        });
        fileMenu.add(newFormOption);

        openButton.setText("Open");
        openButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openButtonActionPerformed(evt);
            }
        });
        fileMenu.add(openButton);

        saveFormOption.setText("Save");
        saveFormOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveFormOptionActionPerformed(evt);
            }
        });
        fileMenu.add(saveFormOption);

        printDoc.setText("Print");
        printDoc.setToolTipText("");
        printDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printDocActionPerformed(evt);
            }
        });
        fileMenu.add(printDoc);

        exitOption.setText("Exit");
        exitOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitOptionActionPerformed(evt);
            }
        });
        fileMenu.add(exitOption);

        menuBar.add(fileMenu);

        helpMenu.setBackground(new java.awt.Color(255, 255, 255));
        helpMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        helpMenu.setText("Help");
        helpMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        helpMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        instructionsOption.setText("Instructions");
        instructionsOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructionsOptionActionPerformed(evt);
            }
        });
        helpMenu.add(instructionsOption);

        legendItem.setText("Legend");
        legendItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                legendItemActionPerformed(evt);
            }
        });
        helpMenu.add(legendItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainProgramPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainProgramPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void locationNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationNameTextFieldActionPerformed

    private void lengthDeadSpaceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lengthDeadSpaceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lengthDeadSpaceTextFieldActionPerformed

    private void calculateBricksNeededActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateBricksNeededActionPerformed
        
       try
       {
           //Add location name to ArrayList
          locationNamesArrayList.add(locationNameTextField.getText());             

    // <editor-fold defaultstate="collapsed" desc="Calculate Brick Dimensions"> 
            brickLength = Double.parseDouble(lengthBrickTextField1.getText());
            brickWidth = Double.parseDouble(widthBrickTextField1.getText());      
            brickArea = brickLength * brickWidth;
            brickDim.add(brickArea);
            System.out.println(brickArea);
       
        
         // </editor-fold> 
         
          // <editor-fold defaultstate="collapsed" desc="Calculate Sections"> 
           sectionLength = Double.parseDouble(lengthSectionTextField.getText());
           sectionWidth = Double.parseDouble(widthSectionTextField.getText());  
           sectionLength = sectionLength * inches;
           sectionWidth = sectionWidth * inches;      
           sectionArea = sectionLength * sectionWidth;
           sectionDim.add(sectionArea);
           System.out.println(sectionArea);
       
        
         // </editor-fold> 
        
          // <editor-fold defaultstate="collapsed" desc="Calculate Voids"> 
        //Calculate Voids----------------------------------------------
        deadSpaceLength =Double.parseDouble(lengthDeadSpaceTextField.getText());
        deadSpaceWidth = Double.parseDouble(widthDeadSpaceTextField.getText()); 
        deadSpaceLength = deadSpaceLength * inches;
        deadSpaceWidth = deadSpaceWidth * inches;      
        deadSpaceArea = deadSpaceLength * deadSpaceWidth;
        voidDim.add(deadSpaceArea);
        System.out.println(deadSpaceArea);
       
        // </editor-fold>  
        
   // <editor-fold defaultstate="collapsed" desc="Calculate Final Brick Number"> 
        //------------------------------------------------------------------///
        mortarGap = (sectionArea / brickArea) * 3; //Calculate the mortar between each brick
        sectionArea = (sectionArea - deadSpaceArea) - mortarGap; //Subtract the mortar gap from brick area      
        totalBricks = Math.round(sectionArea / brickArea); //Calculate total bricks and round to the nearest whole number
        String brickConvert = Double.toString(totalBricks);//Convert double to string format     
        brickResultField.setText("Total Bricks: " + brickConvert + " Bricks");//Display brick results
        
        finalBrickNumber = totalBricks;
        countBricks += totalBricks;//Counts brick each iteration
        brickTotalList.add(totalBricks);//Adds final brick number to list.
        
        model.clear();
        // </editor-fold>          
        
       }catch(Exception e)//Catch exception if boxes are incomplete
       {          
               JOptionPane.showMessageDialog(null,"All boxes bust be completed!"
                       + "\n\n-Enter 0 for unknown dimensions\n"
                       + "-Enter N/A for unknown location", "Invalid Entry", 
                       JOptionPane.INFORMATION_MESSAGE);           
       }   
        // </editor-fold>   

    }//GEN-LAST:event_calculateBricksNeededActionPerformed

    private void totalBricksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalBricksButtonActionPerformed
        String convertTotalBricks = Double.toString(countBricks);
        brickTracker.add(convertTotalBricks);
        displayTotalBricksTextBox.setText("Total Bricks: " + 
                convertTotalBricks + " Bricks");
    }//GEN-LAST:event_totalBricksButtonActionPerformed

    private void instructionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructionsButtonActionPerformed
      new  InstructionsForm().setVisible(true);//Set form to visble for viewing
    }//GEN-LAST:event_instructionsButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
       
       int reply = JOptionPane.showConfirmDialog(null, 
                "Do you Wish to Exit?","", JOptionPane.YES_NO_CANCEL_OPTION);
       if (reply == JOptionPane.NO_OPTION || reply == JOptionPane.CANCEL_OPTION) 
       {
         
       } else {
       JOptionPane.showMessageDialog(null, "GOODBYE");
       System.exit(0);
       }
        
    }//GEN-LAST:event_closeButtonActionPerformed

    private void displayListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayListButtonActionPerformed
        // <editor-fold defaultstate="collapsed" desc="Display List">  
        model.clear();//Clear list befor displaying to prevent replication
        for ( int i = 0; i < brickTracker.size(); i++ ){
            model.addElement("Location: " + locationNamesArrayList.get(i)+
                    " Brick Total: " +  brickTotalList.get(i));
        }
        brickList.setModel(model);
        //Set all text boxes to blank
        lengthBrickTextField1.setText("");
        widthBrickTextField1.setText("");
        lengthSectionTextField.setText("");
        widthSectionTextField.setText(""); 
        lengthDeadSpaceTextField.setText("");
        widthDeadSpaceTextField.setText("");
        displayTotalBricksTextBox.setText("");
        brickResultField.setText("");
        locationNameTextField.setText("");
         // </editor-fold>   
        
    }//GEN-LAST:event_displayListButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // <editor-fold defaultstate="collapsed" desc="Clear Form">
        //Clear entire form
        lengthBrickTextField1.setText("");
        widthBrickTextField1.setText("");
        lengthSectionTextField.setText("");
        widthSectionTextField.setText(""); 
        lengthDeadSpaceTextField.setText("");
        widthDeadSpaceTextField.setText("");
        displayTotalBricksTextBox.setText("");
        brickResultField.setText("");
        locationNameTextField.setText("");
         // </editor-fold>   
    }//GEN-LAST:event_clearButtonActionPerformed

    private void finishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishButtonActionPerformed
        
        // <editor-fold defaultstate="collapsed" desc="Write to Document">
        //Add total bricks needed to list box  
      
        model.addElement("*****************************");
        model.addElement(" ");
        model.addElement("\n\nTotal Bricks Needed: " + countBricks + " Bricks");
         
        brickList.setModel(model);
        //Set all text boxes to blank
        lengthBrickTextField1.setText("");
        widthBrickTextField1.setText("");
        lengthSectionTextField.setText("");
        widthSectionTextField.setText(""); 
        lengthDeadSpaceTextField.setText("");
        widthDeadSpaceTextField.setText("");
        displayTotalBricksTextBox.setText("");
        brickResultField.setText("");
        locationNameTextField.setText("");               
// </editor-fold>   
    }//GEN-LAST:event_finishButtonActionPerformed
//Exit Program using menu bar-----------------------------------------------------
    private void exitOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitOptionActionPerformed
        System.exit(0); 
    }//GEN-LAST:event_exitOptionActionPerformed

    private void instructionsOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructionsOptionActionPerformed
       new  InstructionsForm().setVisible(true);//Set form to visble for viewing  
    }//GEN-LAST:event_instructionsOptionActionPerformed

    private void newFormOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newFormOptionActionPerformed
         // <editor-fold defaultstate="collapsed" desc="Alternate Clear Form">
        //Clear entire form
        lengthBrickTextField1.setText("");
        widthBrickTextField1.setText("");
        lengthSectionTextField.setText("");
        widthSectionTextField.setText(""); 
        lengthDeadSpaceTextField.setText("");
        widthDeadSpaceTextField.setText("");
        displayTotalBricksTextBox.setText("");
        brickResultField.setText("");
        locationNameTextField.setText("");
         // </editor-fold>   
    }//GEN-LAST:event_newFormOptionActionPerformed

    private void saveFormOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveFormOptionActionPerformed
       saveDocPanel.setVisible(true);  //Set panel to visible  
       percentLabel.setText("0%");//Reset label text
       saveDocProgressBar.setValue(0);//Reset progress bar to 0 value
       saveButton.setVisible(true);//Set save button to visible 
       cancelButton.setVisible(true);//Set cancel button to visible 
       okButton.setVisible(false);//Set ok button to invisible      
       enterDocNameTextBox.setText("");
    }//GEN-LAST:event_saveFormOptionActionPerformed

    private void lengthBrickTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lengthBrickTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lengthBrickTextField1ActionPerformed

    private void brickTypesComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brickTypesComboBoxActionPerformed
        // <editor-fold defaultstate="collapsed" desc="ComboBox Menu Items">
        if(evt.getSource() == brickTypesComboBox){
            String items = (String)brickTypesComboBox.getSelectedItem();
            switch(items)/*Controls the flow of items in the combo box and adds
            dimensions to text boxes*/
            {
                case "":
                lengthBrickTextField1.setText("");
                widthBrickTextField1.setText("");
                break;
                case "Modular(2-1/4 x 7-5/8":
                lengthBrickTextField1.setText("7.625");
                widthBrickTextField1.setText("2.25");
                break;
                case "Standard(2-1/4  x 8":
                lengthBrickTextField1.setText("8");
                widthBrickTextField1.setText("2.25");
                break;
                case "Jumbo Modular(2-3/4 x 7-5/8":
                lengthBrickTextField1.setText("7.625");
                widthBrickTextField1.setText("2.75");
                break;
                case "Jumbo Standard(2-3/4 x 8":
                lengthBrickTextField1.setText("8");
                widthBrickTextField1.setText("2.75");
                break;
                case "Jumbo Standard PLT3(2-5/8 x 8":
                lengthBrickTextField1.setText("8");
                widthBrickTextField1.setText("2.625");
                break;
                case "Slim Jumbo Modular(2-3/4 x 7-5/8":
                lengthBrickTextField1.setText("7.625");
                widthBrickTextField1.setText("2.75");
                break;
                case "Queen(2-3/4 x 9-5/8":
                lengthBrickTextField1.setText("9.625");
                widthBrickTextField1.setText("2.75");
                break;
                case  "Roman(1-5/8 x 11-5/8":
                lengthBrickTextField1.setText("11.625");
                widthBrickTextField1.setText("1.625");
                break;
                case "Norman(2-1/4 x 11-5/8":
                lengthBrickTextField1.setText("11.625");
                widthBrickTextField1.setText("2.25");
                break;

                case "Jumbo Norman(2-3/4 x 11-5/8":
                lengthBrickTextField1.setText("11.625");
                widthBrickTextField1.setText("2.75");
                break;

                case "Slim Jumbo Norman(2-3/4 x 11-5/8":
                lengthBrickTextField1.setText("11.625");
                widthBrickTextField1.setText("2.75");
                break;
                case "Modular Economo(3-5/8 x 7-5/8":
                lengthBrickTextField1.setText("7.625");
                widthBrickTextField1.setText("3.625");
                break;
                case  "Utilty(3-5/8 x 11-5/8":
                lengthBrickTextField1.setText("11.625");
                widthBrickTextField1.setText("3.625");
                break;
                case "Monarch(3-5/8 x 15-5/8":
                lengthBrickTextField1.setText("15.625");
                widthBrickTextField1.setText("3.625");
                break;
                case "Quad(7-5/8 x 7-5/8":
                lengthBrickTextField1.setText("7.625");
                widthBrickTextField1.setText("7.625");
                break;
                case "Ambasador(2-1/4 x 15-5/8":
                lengthBrickTextField1.setText("15.625");
                widthBrickTextField1.setText("2.25");
                break;
                case "Double Utilty(3-5/8 x 15-5/8":
                lengthBrickTextField1.setText("15.625");
                widthBrickTextField1.setText("3.625");
                break;
                case "Double Monarch(7-5/8 x 15-5/8":
                lengthBrickTextField1.setText("15.625");
                widthBrickTextField1.setText("7.625");
                break;
                case "Thru-Wall 1(3-5/8 x 15-5/8":
                lengthBrickTextField1.setText("15.625");
                widthBrickTextField1.setText("3.625");
                break;
                case "Thru-Wall 2(3-5/8 x 15-5/8":
                lengthBrickTextField1.setText("15.625");
                widthBrickTextField1.setText("3.625");
                break;
                case "Thru-Wall 3(7-5/8 x 15-5/8":
                lengthBrickTextField1.setText("15.625");
                widthBrickTextField1.setText("7.625");
                break;
                default:

                break;

            }
        }
        // </editor-fold>
    }//GEN-LAST:event_brickTypesComboBoxActionPerformed

    private void lengthSectionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lengthSectionTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lengthSectionTextFieldActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
         // <editor-fold defaultstate="collapsed" desc="Write to Document">
        //Add total bricks needed to list box  
       
//        model.addElement("*****************************");
//        model.addElement(" ");
//       model.addElement("\n\nTotal Bricks Needed: " + countBricks + "Bricks");
        
//        brickList.setModel(model);

        saveDocPanel.setVisible(true);    
        percentLabel.setText("0%");
        saveDocProgressBar.setValue(0);//Reset progress bar
        saveDocProgressBar.setStringPainted(true);
            try{
                   
                for(int i = 0;i < 101;i++){
                Thread.sleep(20);
                saveDocProgressBar.setValue(i);
               } 
               } catch (Exception ex) {
                 Logger.getLogger(BrickProgram.class.getName()).log
        (Level.SEVERE, null, ex);
               }  
        //Set all text boxes to blank
        lengthBrickTextField1.setText("");
        widthBrickTextField1.setText("");
        lengthSectionTextField.setText("");
        widthSectionTextField.setText(""); 
        lengthDeadSpaceTextField.setText("");
        widthDeadSpaceTextField.setText("");
        displayTotalBricksTextBox.setText("");
        brickResultField.setText("");
        locationNameTextField.setText("");       
                       
                
                        //percentLabel.setText(Integer.toString(i));
         
             try {
                     String input = "";
                     saveFile.docName = input;
                     input = enterDocNameTextBox.getText();
              //input = JOptionPane.showInputDialog(null,"Enter Document Name");
               //Create new file and writer and buff objects
                 File file = new File( "BrickDocuments/" + input +".txt");        
                 FileWriter writer = new FileWriter(file);        
                 BufferedWriter buff = new BufferedWriter(writer); 
                 PrintWriter printWriter = new PrintWriter(buff);
                 file.createNewFile();
                 for ( int i = 0; i < brickTracker.size(); i++ ){
                 printWriter.print("Location: " + locationNamesArrayList.get(i)+
                    " Brick Total: " +  brickTotalList.get(i));
                    }
                    printWriter.print("\n*****************************\n"
                      + " "
                      + "\nTotal Bricks Needed: " + countBricks + " Bricks");
                    buff.close();
                    writer.close();
                    printWriter.close();                   
             }
               catch (Exception ex) {
                 Logger.getLogger
                (BrickProgram.class.getName()).log(Level.SEVERE, null, ex);
             }
             saveButton.setVisible(false);
             cancelButton.setVisible(false);
             okButton.setVisible(true);
             model.addElement("Document Successfully Written");
// </editor-fold>    
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        saveDocPanel.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        model.clear();
        saveDocPanel.setVisible(false);
    }//GEN-LAST:event_okButtonActionPerformed

    private void printDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printDocActionPerformed
         Runtime runFile = Runtime.getRuntime();
            try {
	         Runtime.getRuntime().exec("notepad BrickDocuments/Hello.txt");
		}
		catch (IOException e) {
			System.out.println(e);
		}
    }//GEN-LAST:event_printDocActionPerformed

    private void openButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openButtonActionPerformed
        String input = JOptionPane.showInputDialog(null, "Enter Document Name",
        "");
        Runtime runFile = Runtime.getRuntime();
         		try {
	         Runtime.getRuntime().exec
                 ("notepad BrickDocuments/" + input + ".txt");
		}
		catch (IOException e) {
			System.out.println(e);
		}
    }//GEN-LAST:event_openButtonActionPerformed

    private void legendItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_legendItemActionPerformed
        new ProgramLegend().setVisible(true);
    }//GEN-LAST:event_legendItemActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BrickProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BrickProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BrickProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BrickProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>      
         
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BrickProgram().setVisible(true);
                   
           
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JPanel brickDimPanel;
    private javax.swing.JList<String> brickList;
    private javax.swing.JTextField brickResultField;
    private javax.swing.JComboBox<String> brickTypesComboBox;
    private javax.swing.JButton calculateBricksNeeded;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel constructionImage;
    private javax.swing.JLabel dimensions;
    private javax.swing.JLabel dimensions1;
    private javax.swing.JLabel dimensions2;
    private javax.swing.JLabel dimensions3;
    private javax.swing.JButton displayListButton;
    private javax.swing.JTextField displayTotalBricksTextBox;
    private javax.swing.JLabel enterDocNameLabel;
    private javax.swing.JTextField enterDocNameTextBox;
    private javax.swing.JMenuItem exitOption;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JButton finishButton;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem instructionsOption;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem legendItem;
    private javax.swing.JTextField lengthBrickTextField1;
    private javax.swing.JTextField lengthDeadSpaceTextField;
    private javax.swing.JLabel lengthDimLabel2;
    private javax.swing.JLabel lengthDimLabel3;
    private javax.swing.JLabel lengthDimLabel4;
    private javax.swing.JLabel lengthDimLabel5;
    private javax.swing.JTextField lengthSectionTextField;
    private javax.swing.JLabel locationBrickTrackerTitle;
    private javax.swing.JTextField locationNameTextField;
    private javax.swing.JPanel locationPanel;
    private javax.swing.JPanel mainProgramPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem newFormOption;
    private javax.swing.JButton okButton;
    private javax.swing.JMenuItem openButton;
    private javax.swing.JLabel percentLabel;
    private javax.swing.JMenuItem printDoc;
    private javax.swing.JButton saveButton;
    private javax.swing.JPanel saveDocPanel;
    private javax.swing.JProgressBar saveDocProgressBar;
    private javax.swing.JLabel saveDocTitle;
    private javax.swing.JMenuItem saveFormOption;
    private javax.swing.JPanel sectionDimPanel;
    private javax.swing.JLabel stepFiveLabel;
    private javax.swing.JLabel stepFourLabel;
    private javax.swing.JLabel stepOneLabel;
    private javax.swing.JLabel stepSixLabel;
    private javax.swing.JLabel stepThreeLabel1;
    private javax.swing.JLabel stepTwoLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton totalBricksButton;
    private javax.swing.JLabel totalLabel2;
    private javax.swing.JPanel voidDimPanel;
    private javax.swing.JTextField voidDimTotal;
    private javax.swing.JTextField widthBrickTextField1;
    private javax.swing.JTextField widthDeadSpaceTextField;
    private javax.swing.JLabel widthDimLabel1;
    private javax.swing.JLabel widthDimLabel2;
    private javax.swing.JLabel widthDimLabel3;
    private javax.swing.JTextField widthSectionTextField;
    // End of variables declaration//GEN-END:variables
}
