/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package brickapplication_orengoanthony;

import java.awt.Window;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;

/**
 *
 * @author Anthony
 */
public class InstructionsForm extends javax.swing.JFrame {

    /**
     * Creates new form InstructionsForm
     */
    public InstructionsForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        instructionsTitle = new javax.swing.JLabel();
        closeInstructionsButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        instructionsTextArea = new javax.swing.JTextArea();
        instructionsBackgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        instructionsTitle.setFont(new java.awt.Font("Microsoft Himalaya", 1, 75)); // NOI18N
        instructionsTitle.setText("Brick Program Instructions");
        getContentPane().add(instructionsTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        closeInstructionsButton.setFont(new java.awt.Font("Microsoft Himalaya", 1, 36)); // NOI18N
        closeInstructionsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brickapplication_orengoanthony/Images/CloseBttn.png"))); // NOI18N
        closeInstructionsButton.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        closeInstructionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeInstructionsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(closeInstructionsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 640, 100, 50));

        instructionsTextArea.setColumns(20);
        instructionsTextArea.setFont(new java.awt.Font("Microsoft Himalaya", 0, 36)); // NOI18N
        instructionsTextArea.setRows(5);
        instructionsTextArea.setText("\nStep 1: Choose Brick type by using the drop down menu of the combo box. \nYou also have the option to input the the brick dimensions manually. Ensure\nyou have the correct length and width before doing so.\n\nStep 2: Input the Location Name. If the location name is unknown place N/A \nin the textfield. Do not leave the textfield blank.\n\nStep 3: Input height and width of the section area. \n\nStep 4: Input the height and width of any voids. Void include doors, windows, \npassageways,ect. Ensure to enter 0 for the height and width if no voids are \npresent.\n\nStep 5: Calculate total bricks for that section. You made need to cycle through \nsteps 1-5 multiple times before proceeding to step 6.\n\nStep 6: Calculate total number of bricks needed for the project.\n\nFinal Step: Display list or finalize the total brick count.\n");
        instructionsTextArea.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(instructionsTextArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 890, 490));

        instructionsBackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brickapplication_orengoanthony/Images/BrickImage.jpg"))); // NOI18N
        instructionsBackgroundImage.setText("jLabel1");
        instructionsBackgroundImage.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 0)));
        getContentPane().add(instructionsBackgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1050, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeInstructionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeInstructionsButtonActionPerformed
       dispose();
       
    }//GEN-LAST:event_closeInstructionsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InstructionsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InstructionsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InstructionsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InstructionsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeInstructionsButton;
    private javax.swing.JLabel instructionsBackgroundImage;
    private javax.swing.JTextArea instructionsTextArea;
    private javax.swing.JLabel instructionsTitle;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
