package brickapplication_orengoanthony;

import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.*; 
import javax.swing.*; 
import java.awt.event.*; 
/**
 *     
 * @author Anthony
 */
public class MainPageBrickProgram extends javax.swing.JFrame {

    /**
     * Creates new form MainPageBrickProgram
     */
    public MainPageBrickProgram() {
        initComponents();
        
        enterButton.setVisible(false);//Set the Enter button to invisible
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loadingBarLabel = new javax.swing.JLabel();
        mainPageTitle = new javax.swing.JLabel();
        enterButton = new javax.swing.JButton();
        progressBar = new javax.swing.JProgressBar();
        mainPageCloseButton = new javax.swing.JButton();
        mainPageBackgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loadingBarLabel.setBackground(new java.awt.Color(255, 255, 255));
        loadingBarLabel.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        loadingBarLabel.setForeground(new java.awt.Color(255, 255, 255));
        loadingBarLabel.setText("99");
        getContentPane().add(loadingBarLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 120, 50));

        mainPageTitle.setFont(new java.awt.Font("Microsoft Himalaya", 1, 100)); // NOI18N
        mainPageTitle.setText("Java Brick Program");
        getContentPane().add(mainPageTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 720, 130));

        enterButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brickapplication_orengoanthony/Images/enterButton.png"))); // NOI18N
        enterButton.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });
        getContentPane().add(enterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, 160, 60));

        progressBar.setBackground(new java.awt.Color(255, 255, 255));
        progressBar.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        getContentPane().add(progressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 400, 60));

        mainPageCloseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brickapplication_orengoanthony/Images/ExitBtn.png"))); // NOI18N
        mainPageCloseButton.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        mainPageCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainPageCloseButtonActionPerformed(evt);
            }
        });
        getContentPane().add(mainPageCloseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 580, 130, 60));

        mainPageBackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brickapplication_orengoanthony/Images/BrickImage.jpg"))); // NOI18N
        mainPageBackgroundImage.setText("jLabel1");
        getContentPane().add(mainPageBackgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainPageCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainPageCloseButtonActionPerformed
        dispose();        
    }//GEN-LAST:event_mainPageCloseButtonActionPerformed

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed
        MainPageBrickProgram.this.dispose();//Close startup page
        new BrickProgram().setVisible(true);//Set brick program page to visible
    }//GEN-LAST:event_enterButtonActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPageBrickProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPageBrickProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPageBrickProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPageBrickProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
         
         MainPageBrickProgram main = new MainPageBrickProgram();
         main.setVisible(true);//Set startup page to visible
         main.progressBar.setStringPainted(true); //Set progress bar to visible
        // main.progressBar.setForeground(Color.blue);
//Start loading progress bar using for loop
       try 
       {
          //Load progress bar by increase progress bar value
          for(int i = 0; i<=100;i++){
              Thread.sleep(70);
              main.loadingBarLabel.setText(Integer.toString(i) + "%");
              main.progressBar.setValue(i);
          }
        } catch (Exception ex)//Catch exception if progress bar fails to load
        {
           Logger.getLogger(
           MainPageBrickProgram.class.getName()).log(Level.SEVERE, null, ex);
        }
         main.enterButton.setVisible(true);//Set enter bar to visible         
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enterButton;
    private javax.swing.JLabel loadingBarLabel;
    private javax.swing.JLabel mainPageBackgroundImage;
    private javax.swing.JButton mainPageCloseButton;
    private javax.swing.JLabel mainPageTitle;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
}
