/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package brickapplication_orengoanthony;

/**
 *
 * @author Anthony
 */
public class ProgramLegend extends javax.swing.JFrame {

    /**
     * Creates new form Instructions
     */
    public ProgramLegend() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeLegendButton = new javax.swing.JButton();
        legendTitle = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        legendtextArea = new javax.swing.JTextArea();
        legendbackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeLegendButton.setFont(new java.awt.Font("Microsoft Himalaya", 1, 36)); // NOI18N
        closeLegendButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brickapplication_orengoanthony/Images/CloseBttn.png"))); // NOI18N
        closeLegendButton.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        closeLegendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeLegendButtonActionPerformed(evt);
            }
        });
        getContentPane().add(closeLegendButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 630, 100, 50));

        legendTitle.setFont(new java.awt.Font("Microsoft Himalaya", 1, 75)); // NOI18N
        legendTitle.setText("Brick Program Legend");
        getContentPane().add(legendTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        jScrollPane2.setFont(new java.awt.Font("Microsoft Himalaya", 1, 48)); // NOI18N

        legendtextArea.setColumns(20);
        legendtextArea.setFont(new java.awt.Font("Microsoft Himalaya", 0, 36)); // NOI18N
        legendtextArea.setRows(5);
        legendtextArea.setText("\nStart Button: Starts program\n\nAdd to Total Button: Calculates and Adds brick number to total bricks needed\n\nTotal Bricks button: Displays the total amount of bricks calculated so far.\n\nClear Form Button: Clears all text input areas of the form.\n\nDisplay List Button: Displays current elements in the Brick Tracker List.\n\nFinish Button:  Displays all  elements, to include section location, from the brickList in the Brick Tracker List; \nDisplays total number of  bricks needed for the project.\n\nInstructions Button: Displays the complete instructions for the program.\n\nClose Button: Closes current form open.\n\nExit Button: Exits and closes entire program.");
        legendtextArea.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(legendtextArea);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 1060, 530));

        legendbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brickapplication_orengoanthony/Images/BrickImage.jpg"))); // NOI18N
        legendbackground.setText("jLabel1");
        getContentPane().add(legendbackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1120, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeLegendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeLegendButtonActionPerformed
        dispose();

    }//GEN-LAST:event_closeLegendButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProgramLegend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProgramLegend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProgramLegend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProgramLegend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProgramLegend().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeLegendButton;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel legendTitle;
    private javax.swing.JLabel legendbackground;
    private javax.swing.JTextArea legendtextArea;
    // End of variables declaration//GEN-END:variables
}
